# Project information
site_name: My Projects & Notes
site_url: https://ignasi.blasi/myprojects&notes/
site_author: Ignasi Blasi
site_description: In this site I will be adding commands, notes and projects that I think they will be useful

theme:
  name: material

  # Static files
  static_templates:
    - 404.html

plugins:
  - search
  - git-revision-date

#Respository
repo_name: ignasiblasimoreno/ignasiblasi
repo_url: https://github.com/ignasiblasimoreno/ignasiblasi
edit_uri: edit/main/docs


# Markdown
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences